---
title: "Halley's Resume"
---
**CONTACT**

Halley Winkler

winklerhr@appstate.edu

**EDUCATION**


* Franklinton High School, Franklinton NC

    + SEPTEMBER 2015 - JUNE 2017

    + Enrolled in 2015 after transferring from Triton Regional High School, Blackwood NJ

    + Honors/AP student and NHS member with an accelerated graduation.


* Appalachian State University, Boone NC

    + AUGUST 2017-PRESENT TIME

    + Undergraduate honors student studying mathematics with a concentration in data analysis. 
Expected graduation date is May of 2021. 



**EXPERIENCE**


* Stemville, Franklin County NC - Volunteer

    + WINTER 2015- SPRING 2016

    + Volunteered through FHS math club at elementary schools, led activities that taught science and math to children.


* Tutor

    + FALL 2016- SPRING 2017

    + Volunteer through North Carolina Virtual Public School tutoring math 1, 2, 3, precalculus, and calculus


* Teaching Assistant

    + FALL 2016

    + Teaching assistant for Honors Earth and Environment Science


* Lab Technician

    + FALL 2016- SPRING 2017

    + Lab technician for FHS science courses


* Dollar General

    + SPRING 2018- PRESENT TIME

    + Lead sales associate responsible for customer service, stocking, and cash management. 


**AWARDS**


* Cell Biology Regional First Place Science Olympiad


* Math 3 NC State Level Competitor 


* Woman's Club Scholarship


* Hugh I. Grant Scholarship


* Franklinton Freemasonry Service Scholarship
